# Generated by Django 5.1.5 on 2025-02-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['created']},
        ),
    ]
